//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketBrain.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocketBrain.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Benjamin Sautermeister.
        /// </summary>
        public static string ApplicationAuthor {
            get {
                return ResourceManager.GetString("ApplicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application helps you to remember all your every day stuff. With no frills..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pocketBRAIN.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        public static string ArchiveTitle {
            get {
                return ResourceManager.GetString("ArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention:.
        /// </summary>
        public static string AttentionTitle {
            get {
                return ResourceManager.GetString("AttentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a backup of your data, which are going to be saved on you OneDrive. You can later restore the data on any device..
        /// </summary>
        public static string BackupInfoText {
            get {
                return ResourceManager.GetString("BackupInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backups.
        /// </summary>
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this app active until the operation is finished. A stable internet connection is required..
        /// </summary>
        public static string CommonBackupWarningText {
            get {
                return ResourceManager.GetString("CommonBackupWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide on lock screen.
        /// </summary>
        public static string ContextMenuHide {
            get {
                return ResourceManager.GetString("ContextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string ContextMenuPinToStart {
            get {
                return ResourceManager.GetString("ContextMenuPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore.
        /// </summary>
        public static string ContextMenuRestore {
            get {
                return ResourceManager.GetString("ContextMenuRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show on lock screen.
        /// </summary>
        public static string ContextMenuShow {
            get {
                return ResourceManager.GetString("ContextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin from start.
        /// </summary>
        public static string ContextMenuUnpinFromStart {
            get {
                return ResourceManager.GetString("ContextMenuUnpinFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string CreateBackupHeaderText {
            get {
                return ResourceManager.GetString("CreateBackupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBodyText {
            get {
                return ResourceManager.GetString("FeedbackBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps@bsautermeister.de.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate pocketBRAIN.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessageText {
            get {
                return ResourceManager.GetString("FeedbackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNoText {
            get {
                return ResourceManager.GetString("FeedbackNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pocketBRAIN Customer Feedback .
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYesText {
            get {
                return ResourceManager.GetString("FeedbackYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string InAppStoreLoading {
            get {
                return ResourceManager.GetString("InAppStoreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no in-app purchases available. Please try again later..
        /// </summary>
        public static string InAppStoreNoProducts {
            get {
                return ResourceManager.GetString("InAppStoreNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchased.
        /// </summary>
        public static string InAppStorePurchased {
            get {
                return ResourceManager.GetString("InAppStorePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in-app store.
        /// </summary>
        public static string InAppStoreTitle {
            get {
                return ResourceManager.GetString("InAppStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Backup &apos;{0}&apos; could not be created. Please check you internet connection..
        /// </summary>
        public static string MessageBoxBackupErrorText {
            get {
                return ResourceManager.GetString("MessageBoxBackupErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Backup &apos;{0}&apos; has been created successfully..
        /// </summary>
        public static string MessageBoxBackupSuccessText {
            get {
                return ResourceManager.GetString("MessageBoxBackupSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear the archive?.
        /// </summary>
        public static string MessageBoxClearCheck {
            get {
                return ResourceManager.GetString("MessageBoxClearCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is copied to the clipboard..
        /// </summary>
        public static string MessageBoxInfoClipboard {
            get {
                return ResourceManager.GetString("MessageBoxInfoClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBoxInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice recognizer is not activated. Please refer to your phone settings..
        /// </summary>
        public static string MessageBoxNoRecUI {
            get {
                return ResourceManager.GetString("MessageBoxNoRecUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Backup &apos;{0}&apos; could ne be restored. Please check you internet connection..
        /// </summary>
        public static string MessageBoxRestoreErrorText {
            get {
                return ResourceManager.GetString("MessageBoxRestoreErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Backup &apos;{0}&apos; has been restored successfully..
        /// </summary>
        public static string MessageBoxRestoreSuccessText {
            get {
                return ResourceManager.GetString("MessageBoxRestoreSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxWarningTitle {
            get {
                return ResourceManager.GetString("MessageBoxWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more apps.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup title.
        /// </summary>
        public static string NameOfBackupHintText {
            get {
                return ResourceManager.GetString("NameOfBackupHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy info.
        /// </summary>
        public static string PrivacyInfo {
            get {
                return ResourceManager.GetString("PrivacyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage10Text {
            get {
                return ResourceManager.GetString("RatingMessage10Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage5Text {
            get {
                return ResourceManager.GetString("RatingMessage5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNoText {
            get {
                return ResourceManager.GetString("RatingNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying pocketBRAIN?.
        /// </summary>
        public static string RatingTitleText {
            get {
                return ResourceManager.GetString("RatingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYesText {
            get {
                return ResourceManager.GetString("RatingYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore.
        /// </summary>
        public static string RestoreBackupHeaderText {
            get {
                return ResourceManager.GetString("RestoreBackupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can restore your data here. Current notes and tiles are going to be removed..
        /// </summary>
        public static string RestoreInfoText {
            get {
                return ResourceManager.GetString("RestoreInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 item.
        /// </summary>
        public static string Settings1Item {
            get {
                return ResourceManager.GetString("Settings1Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 items.
        /// </summary>
        public static string Settings2Items {
            get {
                return ResourceManager.GetString("Settings2Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 items.
        /// </summary>
        public static string Settings4Items {
            get {
                return ResourceManager.GetString("Settings4Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 items (PRO).
        /// </summary>
        public static string Settings6Items {
            get {
                return ResourceManager.GetString("Settings6Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background image.
        /// </summary>
        public static string SettingsBackgroundImageTitle {
            get {
                return ResourceManager.GetString("SettingsBackgroundImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background opacity.
        /// </summary>
        public static string SettingsBackgroundOpacityTitle {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string SettingsDisabled {
            get {
                return ResourceManager.GetString("SettingsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        public static string SettingsEnabled {
            get {
                return ResourceManager.GetString("SettingsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra large (PRO).
        /// </summary>
        public static string SettingsExtraLarge {
            get {
                return ResourceManager.GetString("SettingsExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font size.
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatic word correction.
        /// </summary>
        public static string SettingsKeyboardExtendedAutoCorrectTitle {
            get {
                return ResourceManager.GetString("SettingsKeyboardExtendedAutoCorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string SettingsKeyboardTitle {
            get {
                return ResourceManager.GetString("SettingsKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string SettingsLarge {
            get {
                return ResourceManager.GetString("SettingsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add note button.
        /// </summary>
        public static string SettingsListsAddNoteTitle {
            get {
                return ResourceManager.GetString("SettingsListsAddNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show a button.
        /// </summary>
        public static string SettingsListsExpandButton {
            get {
                return ResourceManager.GetString("SettingsListsExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by shake gesture.
        /// </summary>
        public static string SettingsListsExpandByGesture {
            get {
                return ResourceManager.GetString("SettingsListsExpandByGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by shake gesture and button.
        /// </summary>
        public static string SettingsListsExpandByGestureAndButton {
            get {
                return ResourceManager.GetString("SettingsListsExpandByGestureAndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimize / maximize.
        /// </summary>
        public static string SettingsListsExpandTitle {
            get {
                return ResourceManager.GetString("SettingsListsExpandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hidden (horizontal swipe only).
        /// </summary>
        public static string SettingsListsHideAddButton {
            get {
                return ResourceManager.GetString("SettingsListsHideAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visible.
        /// </summary>
        public static string SettingsListsShowAddButton {
            get {
                return ResourceManager.GetString("SettingsListsShowAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show creation date.
        /// </summary>
        public static string SettingsListsShowCreationDate {
            get {
                return ResourceManager.GetString("SettingsListsShowCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string SettingsListsTitle {
            get {
                return ResourceManager.GetString("SettingsListsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tile.
        /// </summary>
        public static string SettingsLiveTileTitle {
            get {
                return ResourceManager.GetString("SettingsLiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen.
        /// </summary>
        public static string SettingsLockScreenTitle {
            get {
                return ResourceManager.GetString("SettingsLockScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string SettingsMedium {
            get {
                return ResourceManager.GetString("SettingsMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items count.
        /// </summary>
        public static string SettingsMinimiumItemsTitle {
            get {
                return ResourceManager.GetString("SettingsMinimiumItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string SettingsPreview {
            get {
                return ResourceManager.GetString("SettingsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small (PRO).
        /// </summary>
        public static string SettingsSmall {
            get {
                return ResourceManager.GetString("SettingsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap to select from library.
        /// </summary>
        public static string SettingsTapToSelect {
            get {
                return ResourceManager.GetString("SettingsTapToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show number of notes on main tile.
        /// </summary>
        public static string SettingsTileNoteCountTitle {
            get {
                return ResourceManager.GetString("SettingsTileNoteCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXL (PRO).
        /// </summary>
        public static string SettingsXXL {
            get {
                return ResourceManager.GetString("SettingsXXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support and feedback.
        /// </summary>
        public static string SupportAndFeedback {
            get {
                return ResourceManager.GetString("SupportAndFeedback", resourceCulture);
            }
        }
    }
}
