//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketBrain.App.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocketBrain.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about ähnelt.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by Benjamin Sautermeister ähnelt.
        /// </summary>
        public static string ApplicationAuthor {
            get {
                return ResourceManager.GetString("ApplicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This application helps you to remember all your every day stuff. With no frills. ähnelt.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pocketBRAIN ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.5 ähnelt.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die archive ähnelt.
        /// </summary>
        public static string ArchiveTitle {
            get {
                return ResourceManager.GetString("ArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete ähnelt.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hide on lock screen ähnelt.
        /// </summary>
        public static string ContextMenuHide {
            get {
                return ResourceManager.GetString("ContextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pin to start ähnelt.
        /// </summary>
        public static string ContextMenuPinToStart {
            get {
                return ResourceManager.GetString("ContextMenuPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die restore ähnelt.
        /// </summary>
        public static string ContextMenuRestore {
            get {
                return ResourceManager.GetString("ContextMenuRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show on lock screen ähnelt.
        /// </summary>
        public static string ContextMenuShow {
            get {
                return ResourceManager.GetString("ContextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unpin from start ähnelt.
        /// </summary>
        public static string ContextMenuUnpinFromStart {
            get {
                return ResourceManager.GetString("ContextMenuUnpinFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contributors ähnelt.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Untitled ähnelt.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///--------------------------------- ähnelt.
        /// </summary>
        public static string FeedbackBodyText {
            get {
                return ResourceManager.GetString("FeedbackBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die apps@bsautermeister.de ähnelt.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry to hear you didn&apos;t want to rate pocketBRAIN.
        ///
        ///Tell us about your experience or suggest how we can make it even better. ähnelt.
        /// </summary>
        public static string FeedbackMessageText {
            get {
                return ResourceManager.GetString("FeedbackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no thanks ähnelt.
        /// </summary>
        public static string FeedbackNoText {
            get {
                return ResourceManager.GetString("FeedbackNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pocketBRAIN Customer Feedback  ähnelt.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can we make it better? ähnelt.
        /// </summary>
        public static string FeedbackTitleText {
            get {
                return ResourceManager.GetString("FeedbackTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die give feedback ähnelt.
        /// </summary>
        public static string FeedbackYesText {
            get {
                return ResourceManager.GetString("FeedbackYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to clear the archive? ähnelt.
        /// </summary>
        public static string MessageBoxClearCheck {
            get {
                return ResourceManager.GetString("MessageBoxClearCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The content is copied to the clipboard. ähnelt.
        /// </summary>
        public static string MessageBoxInfoClipboard {
            get {
                return ResourceManager.GetString("MessageBoxInfoClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string MessageBoxInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice recognizer is not activated. Please refer to your phone settings. ähnelt.
        /// </summary>
        public static string MessageBoxNoRecUI {
            get {
                return ResourceManager.GetString("MessageBoxNoRecUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string MessageBoxWarningTitle {
            get {
                return ResourceManager.GetString("MessageBoxWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more apps ähnelt.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die privacy info ähnelt.
        /// </summary>
        public static string PrivacyInfo {
            get {
                return ResourceManager.GetString("PrivacyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rate and review ähnelt.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation? ähnelt.
        /// </summary>
        public static string RatingMessage10Text {
            get {
                return ResourceManager.GetString("RatingMessage10Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better! ähnelt.
        /// </summary>
        public static string RatingMessage5Text {
            get {
                return ResourceManager.GetString("RatingMessage5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no thanks ähnelt.
        /// </summary>
        public static string RatingNoText {
            get {
                return ResourceManager.GetString("RatingNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enjoying pocketBRAIN? ähnelt.
        /// </summary>
        public static string RatingTitleText {
            get {
                return ResourceManager.GetString("RatingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rate 5 stars ähnelt.
        /// </summary>
        public static string RatingYesText {
            get {
                return ResourceManager.GetString("RatingYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 item ähnelt.
        /// </summary>
        public static string Settings1Item {
            get {
                return ResourceManager.GetString("Settings1Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 items ähnelt.
        /// </summary>
        public static string Settings2Items {
            get {
                return ResourceManager.GetString("Settings2Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 items ähnelt.
        /// </summary>
        public static string Settings4Items {
            get {
                return ResourceManager.GetString("Settings4Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 6 items ähnelt.
        /// </summary>
        public static string Settings6Items {
            get {
                return ResourceManager.GetString("Settings6Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die background image ähnelt.
        /// </summary>
        public static string SettingsBackgroundImageTitle {
            get {
                return ResourceManager.GetString("SettingsBackgroundImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die disabled ähnelt.
        /// </summary>
        public static string SettingsDisabled {
            get {
                return ResourceManager.GetString("SettingsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enabled ähnelt.
        /// </summary>
        public static string SettingsEnabled {
            get {
                return ResourceManager.GetString("SettingsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die extra large ähnelt.
        /// </summary>
        public static string SettingsExtraLarge {
            get {
                return ResourceManager.GetString("SettingsExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die font size ähnelt.
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die automatic word correction ähnelt.
        /// </summary>
        public static string SettingsKeyboardExtendedAutoCorrectTitle {
            get {
                return ResourceManager.GetString("SettingsKeyboardExtendedAutoCorrectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyboard ähnelt.
        /// </summary>
        public static string SettingsKeyboardTitle {
            get {
                return ResourceManager.GetString("SettingsKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die large ähnelt.
        /// </summary>
        public static string SettingsLarge {
            get {
                return ResourceManager.GetString("SettingsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add note button ähnelt.
        /// </summary>
        public static string SettingsListsAddNoteTitle {
            get {
                return ResourceManager.GetString("SettingsListsAddNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show a button ähnelt.
        /// </summary>
        public static string SettingsListsExpandButton {
            get {
                return ResourceManager.GetString("SettingsListsExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by shake geasture ähnelt.
        /// </summary>
        public static string SettingsListsExpandByGesture {
            get {
                return ResourceManager.GetString("SettingsListsExpandByGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by shake geasture and button ähnelt.
        /// </summary>
        public static string SettingsListsExpandByGestureAndButton {
            get {
                return ResourceManager.GetString("SettingsListsExpandByGestureAndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minimize / maximize ähnelt.
        /// </summary>
        public static string SettingsListsExpandTitle {
            get {
                return ResourceManager.GetString("SettingsListsExpandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hidden (horizontal swipe only) ähnelt.
        /// </summary>
        public static string SettingsListsHideAddButton {
            get {
                return ResourceManager.GetString("SettingsListsHideAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die visible ähnelt.
        /// </summary>
        public static string SettingsListsShowAddButton {
            get {
                return ResourceManager.GetString("SettingsListsShowAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show creation date ähnelt.
        /// </summary>
        public static string SettingsListsShowCreationDate {
            get {
                return ResourceManager.GetString("SettingsListsShowCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lists ähnelt.
        /// </summary>
        public static string SettingsListsTitle {
            get {
                return ResourceManager.GetString("SettingsListsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Live Tile ähnelt.
        /// </summary>
        public static string SettingsLiveTileTitle {
            get {
                return ResourceManager.GetString("SettingsLiveTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock screen ähnelt.
        /// </summary>
        public static string SettingsLockScreenTitle {
            get {
                return ResourceManager.GetString("SettingsLockScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die medium ähnelt.
        /// </summary>
        public static string SettingsMedium {
            get {
                return ResourceManager.GetString("SettingsMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minimum items count ähnelt.
        /// </summary>
        public static string SettingsMinimiumItemsTitle {
            get {
                return ResourceManager.GetString("SettingsMinimiumItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die preview ähnelt.
        /// </summary>
        public static string SettingsPreview {
            get {
                return ResourceManager.GetString("SettingsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die small ähnelt.
        /// </summary>
        public static string SettingsSmall {
            get {
                return ResourceManager.GetString("SettingsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tap to select from library ähnelt.
        /// </summary>
        public static string SettingsTapToSelect {
            get {
                return ResourceManager.GetString("SettingsTapToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show number of notes on main tile ähnelt.
        /// </summary>
        public static string SettingsTileNoteCountTitle {
            get {
                return ResourceManager.GetString("SettingsTileNoteCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die support and feedback ähnelt.
        /// </summary>
        public static string SupportAndFeedback {
            get {
                return ResourceManager.GetString("SupportAndFeedback", resourceCulture);
            }
        }
    }
}
